/**
 * Simplified PDF generation for Schedule E
 * Using plain text content instead of complex layouts
 */

import {
  ScheduleEData,
  ScheduleESummary,
} from "./types";
import { formatTaxAmount } from "./calculations";

/**
 * Generate plain text Schedule E content for PDF conversion
 */
export function generateScheduleEText(data: ScheduleEData): string {
  const lines = [];

  // Header
  lines.push("SCHEDULE E (Form 1040)");
  lines.push("Supplemental Income and Loss");
  lines.push(`Tax Year ${data.taxYear}`);
  lines.push("");

  // Property Information
  lines.push("Property Information:");
  lines.push(`Address: ${data.property.address.street}${data.property.address.streetLine2 ? `, ${data.property.address.streetLine2}` : ''}, ${data.property.address.city}, ${data.property.address.state} ${data.property.address.zipCode}`);
  lines.push(`Property Type: ${data.property.propertyType}`);
  lines.push(`Purchase Date: ${data.property.purchaseDate}`);
  lines.push("");

  // Schedule E Lines
  lines.push("SCHEDULE E - Rental Income and Expenses:");
  lines.push("─".repeat(60));

  lines.push(`Line 3. Rents received                           ${formatTaxAmount(data.income.rentalIncome).padStart(12)}`);
  lines.push("");

  lines.push("EXPENSES:");
  lines.push(`Line 5. Advertising                             ${formatTaxAmount(data.expenses.advertising).padStart(12)}`);
  lines.push(`Line 6. Auto and travel                         ${formatTaxAmount(data.expenses.autoAndTravel).padStart(12)}`);
  lines.push(`Line 7. Cleaning and maintenance                ${formatTaxAmount(data.expenses.cleaningAndMaintenance).padStart(12)}`);
  lines.push(`Line 8. Commissions                             ${formatTaxAmount(data.expenses.commissions).padStart(12)}`);
  lines.push(`Line 9. Insurance                               ${formatTaxAmount(data.expenses.insurance).padStart(12)}`);
  lines.push(`Line 10. Legal and other professional fees      ${formatTaxAmount(data.expenses.legal).padStart(12)}`);
  lines.push(`Line 11. Management fees                        ${formatTaxAmount(data.expenses.managementFees).padStart(12)}`);
  lines.push(`Line 12. Mortgage interest paid to banks, etc.  ${formatTaxAmount(data.expenses.mortgageInterest).padStart(12)}`);
  lines.push(`Line 13. Other interest                         ${formatTaxAmount(data.expenses.otherInterest).padStart(12)}`);
  lines.push(`Line 14. Repairs                                ${formatTaxAmount(data.expenses.repairs).padStart(12)}`);
  lines.push(`Line 15. Supplies                               ${formatTaxAmount(data.expenses.supplies).padStart(12)}`);
  lines.push(`Line 16. Taxes                                  ${formatTaxAmount(data.expenses.taxes).padStart(12)}`);
  lines.push(`Line 17. Utilities                              ${formatTaxAmount(data.expenses.utilities).padStart(12)}`);
  lines.push(`Line 18. Depreciation expense                   ${formatTaxAmount(data.expenses.depreciation).padStart(12)}`);
  lines.push(`Line 19. Other                                  ${formatTaxAmount(data.expenses.other).padStart(12)}`);

  lines.push("─".repeat(60));
  lines.push(`Line 20. Total expenses                         ${formatTaxAmount(data.totals.totalExpenses).padStart(12)}`);
  lines.push("");
  lines.push(`Line 21. Income or (loss) from rental activities:`);
  const netIncome = data.totals.netIncome < 0
    ? `(${formatTaxAmount(Math.abs(data.totals.netIncome))})`
    : formatTaxAmount(data.totals.netIncome);
  lines.push(`         ${netIncome.padStart(12)}`);

  // Depreciation Details
  if (data.depreciation) {
    lines.push("");
    lines.push("DEPRECIATION DETAILS:");
    lines.push(`Depreciable Basis:              ${formatTaxAmount(data.depreciation.depreciableBasis)}`);
    lines.push(`Month Placed in Service:        ${data.depreciation.monthPlacedInService}`);
    lines.push(`Current Year Depreciation:      ${formatTaxAmount(data.depreciation.currentYearDepreciation)}`);
  }

  lines.push("");
  lines.push("─".repeat(60));
  lines.push("Generated by PropOwl - The wise way to manage rentals");
  lines.push(`Report generated on: ${new Date().toLocaleDateString()}`);

  return lines.join("\n");
}

/**
 * Generate multi-property summary text
 */
export function generateScheduleESummaryText(summary: ScheduleESummary): string {
  const lines = [];

  // Header
  lines.push("SCHEDULE E SUMMARY - MULTI-PROPERTY");
  lines.push(`Tax Year ${summary.taxYear}`);
  lines.push("");

  // Summary Table
  lines.push("PORTFOLIO SUMMARY:");
  lines.push("─".repeat(80));
  lines.push("Property".padEnd(35) + "Income".padStart(10) + "Expenses".padStart(12) + "Deprec.".padStart(10) + "Net".padStart(10));
  lines.push("─".repeat(80));

  summary.properties.forEach((property) => {
    const address = `${property.property.address.street}${property.property.address.streetLine2 ? `, ${property.property.address.streetLine2}` : ''}, ${property.property.address.city}`;
    const shortAddress = address.length > 33 ? address.substring(0, 30) + "..." : address;

    const income = formatTaxAmount(property.income.rentalIncome);
    const expenses = formatTaxAmount(property.totals.totalExpenses - property.expenses.depreciation);
    const depreciation = formatTaxAmount(property.expenses.depreciation);
    const net = property.totals.netIncome < 0
      ? `(${formatTaxAmount(Math.abs(property.totals.netIncome))})`
      : formatTaxAmount(property.totals.netIncome);

    lines.push(shortAddress.padEnd(35) + income.padStart(10) + expenses.padStart(12) + depreciation.padStart(10) + net.padStart(10));
  });

  lines.push("─".repeat(80));
  const totalIncome = formatTaxAmount(summary.totals.totalIncome);
  const totalExpenses = formatTaxAmount(summary.totals.totalExpenses - summary.totals.totalDepreciation);
  const totalDepreciation = formatTaxAmount(summary.totals.totalDepreciation);
  const totalNet = summary.totals.netIncome < 0
    ? `(${formatTaxAmount(Math.abs(summary.totals.netIncome))})`
    : formatTaxAmount(summary.totals.netIncome);

  lines.push("TOTAL".padEnd(35) + totalIncome.padStart(10) + totalExpenses.padStart(12) + totalDepreciation.padStart(10) + totalNet.padStart(10));

  lines.push("");
  lines.push("INDIVIDUAL PROPERTY SCHEDULE E DATA:");
  lines.push("═".repeat(80));

  // Individual property details
  summary.properties.forEach((property, index) => {
    lines.push("");
    lines.push(`PROPERTY ${String.fromCharCode(65 + index)}: ${property.property.address.street}${property.property.address.streetLine2 ? `, ${property.property.address.streetLine2}` : ''}, ${property.property.address.city}, ${property.property.address.state}`);
    lines.push("─".repeat(60));
    lines.push(`Line 3. Rents received                           ${formatTaxAmount(property.income.rentalIncome).padStart(12)}`);
    lines.push(`Line 20. Total expenses                          ${formatTaxAmount(property.totals.totalExpenses).padStart(12)}`);
    const netIncome = property.totals.netIncome < 0
      ? `(${formatTaxAmount(Math.abs(property.totals.netIncome))})`
      : formatTaxAmount(property.totals.netIncome);
    lines.push(`Line 21. Income or (loss)                        ${netIncome.padStart(12)}`);
  });

  lines.push("");
  lines.push("─".repeat(80));
  lines.push("Generated by PropOwl - The wise way to manage rentals");
  lines.push(`Report generated on: ${new Date().toLocaleDateString()}`);

  return lines.join("\n");
}

/**
 * Generate filename for text/PDF reports
 */
export function generateReportFilename(data: ScheduleEData | ScheduleESummary, format: 'txt' | 'pdf' = 'pdf'): string {
  let taxYear: number;
  let isMultiple: boolean;

  if ("properties" in data) {
    // ScheduleESummary
    taxYear = data.taxYear;
    isMultiple = data.properties.length > 1;
  } else {
    // ScheduleEData
    taxYear = data.taxYear;
    isMultiple = false;
  }

  const base = isMultiple ? "schedule-e-summary" : "schedule-e-property";
  const extension = format === 'pdf' ? 'pdf' : 'txt';

  return `${base}-${taxYear}.${extension}`;
}

/**
 * Convert Schedule E data to professional HTML for PDF generation
 */
export function scheduleEToHTML(data: ScheduleEData): string {
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>Schedule E (Form 1040) - ${data.taxYear}</title>
      <style>
        @page {
          size: A4;
          margin: 1in 0.75in;
        }
        body {
          font-family: Arial, sans-serif;
          font-size: 11px;
          line-height: 1.3;
          margin: 0;
          color: #000;
          -webkit-print-color-adjust: exact !important;
          print-color-adjust: exact !important;
          color-adjust: exact !important;
        }
        * {
          -webkit-print-color-adjust: exact !important;
          print-color-adjust: exact !important;
          color-adjust: exact !important;
        }
        @media print {
          body {
            font-size: 10px;
            line-height: 1.2;
          }
          .schedule-table {
            font-size: 9px;
          }
          .header {
            margin-bottom: 15px;
          }
          .property-info {
            margin: 10px 0;
            padding: 8px;
          }
        }
        .header {
          text-align: center;
          margin-bottom: 20px;
          border-bottom: 2px solid #000;
          padding-bottom: 10px;
        }
        .form-title {
          font-size: 16px;
          font-weight: bold;
          margin: 5px 0;
        }
        .subtitle {
          font-size: 12px;
          margin: 5px 0;
        }
        .property-info {
          background: #f5f5f5;
          padding: 10px;
          margin: 15px 0;
          border: 1px solid #ccc;
        }
        .schedule-table {
          width: 100%;
          border-collapse: collapse;
          margin: 15px 0;
        }
        .schedule-table th, .schedule-table td {
          border: 1px solid #000;
          padding: 5px;
          text-align: left;
        }
        .schedule-table th {
          background: #f0f0f0;
          font-weight: bold;
        }
        .line-number {
          width: 50px;
          text-align: center;
          font-weight: bold;
        }
        .amount {
          width: 100px;
          text-align: right;
          font-family: 'Courier New', monospace;
        }
        .total-row {
          background: #f0f0f0;
          font-weight: bold;
        }
        .income-row {
          background: #e8f5e8;
        }
        .expense-row {
          background: #fff5f5;
        }
        .net-income {
          background: #e8f5ff;
          font-weight: bold;
          font-size: 12px;
        }
        .footer {
          margin-top: 30px;
          padding-top: 15px;
          border-top: 1px solid #ccc;
          font-size: 9px;
          text-align: center;
          color: #666;
        }
        .depreciation-section {
          margin-top: 20px;
          padding: 10px;
          border: 1px solid #ccc;
          background: #f9f9f9;
        }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="form-title">SCHEDULE E</div>
        <div class="form-title">(Form 1040)</div>
        <div class="subtitle">Supplemental Income and Loss</div>
        <div class="subtitle">Tax Year ${data.taxYear}</div>
      </div>

      <div class="property-info">
        <strong>Property A:</strong> ${data.property.address.street}${data.property.address.streetLine2 ? `, ${data.property.address.streetLine2}` : ''}, ${data.property.address.city}, ${data.property.address.state} ${data.property.address.zipCode}<br>
        <strong>Property Type:</strong> ${data.property.propertyType}<br>
        <strong>Purchase Date:</strong> ${new Date(data.property.purchaseDate).toLocaleDateString()}
      </div>

      <table class="schedule-table">
        <thead>
          <tr>
            <th class="line-number">Line</th>
            <th>Description</th>
            <th class="amount">Amount</th>
          </tr>
        </thead>
        <tbody>
          <tr class="income-row">
            <td class="line-number">3</td>
            <td><strong>Rents received</strong></td>
            <td class="amount">${formatTaxAmount(data.income.rentalIncome)}</td>
          </tr>

          <tr style="height: 10px;"><td colspan="3"></td></tr>

          <tr class="expense-row">
            <td class="line-number">5</td>
            <td>Advertising</td>
            <td class="amount">${formatTaxAmount(data.expenses.advertising)}</td>
          </tr>
          <tr class="expense-row">
            <td class="line-number">6</td>
            <td>Auto and travel</td>
            <td class="amount">${formatTaxAmount(data.expenses.autoAndTravel)}</td>
          </tr>
          <tr class="expense-row">
            <td class="line-number">7</td>
            <td>Cleaning and maintenance</td>
            <td class="amount">${formatTaxAmount(data.expenses.cleaningAndMaintenance)}</td>
          </tr>
          <tr class="expense-row">
            <td class="line-number">8</td>
            <td>Commissions</td>
            <td class="amount">${formatTaxAmount(data.expenses.commissions)}</td>
          </tr>
          <tr class="expense-row">
            <td class="line-number">9</td>
            <td>Insurance</td>
            <td class="amount">${formatTaxAmount(data.expenses.insurance)}</td>
          </tr>
          <tr class="expense-row">
            <td class="line-number">10</td>
            <td>Legal and other professional fees</td>
            <td class="amount">${formatTaxAmount(data.expenses.legal)}</td>
          </tr>
          <tr class="expense-row">
            <td class="line-number">11</td>
            <td>Management fees</td>
            <td class="amount">${formatTaxAmount(data.expenses.managementFees)}</td>
          </tr>
          <tr class="expense-row">
            <td class="line-number">12</td>
            <td>Mortgage interest paid to banks, etc.</td>
            <td class="amount">${formatTaxAmount(data.expenses.mortgageInterest)}</td>
          </tr>
          <tr class="expense-row">
            <td class="line-number">13</td>
            <td>Other interest</td>
            <td class="amount">${formatTaxAmount(data.expenses.otherInterest)}</td>
          </tr>
          <tr class="expense-row">
            <td class="line-number">14</td>
            <td>Repairs</td>
            <td class="amount">${formatTaxAmount(data.expenses.repairs)}</td>
          </tr>
          <tr class="expense-row">
            <td class="line-number">15</td>
            <td>Supplies</td>
            <td class="amount">${formatTaxAmount(data.expenses.supplies)}</td>
          </tr>
          <tr class="expense-row">
            <td class="line-number">16</td>
            <td>Taxes</td>
            <td class="amount">${formatTaxAmount(data.expenses.taxes)}</td>
          </tr>
          <tr class="expense-row">
            <td class="line-number">17</td>
            <td>Utilities</td>
            <td class="amount">${formatTaxAmount(data.expenses.utilities)}</td>
          </tr>
          <tr class="expense-row" style="background: #ffe8e8;">
            <td class="line-number">18</td>
            <td><strong>Depreciation expense</strong></td>
            <td class="amount"><strong>${formatTaxAmount(data.expenses.depreciation)}</strong></td>
          </tr>
          <tr class="expense-row">
            <td class="line-number">19</td>
            <td>Other</td>
            <td class="amount">${formatTaxAmount(data.expenses.other)}</td>
          </tr>

          <tr class="total-row">
            <td class="line-number">20</td>
            <td><strong>Total expenses</strong></td>
            <td class="amount"><strong>${formatTaxAmount(data.totals.totalExpenses)}</strong></td>
          </tr>

          <tr class="net-income">
            <td class="line-number">21</td>
            <td><strong>Income or (loss) from rental real estate activities</strong></td>
            <td class="amount"><strong>${data.totals.netIncome < 0 ? `(${formatTaxAmount(Math.abs(data.totals.netIncome))})` : formatTaxAmount(data.totals.netIncome)}</strong></td>
          </tr>
        </tbody>
      </table>

      ${data.depreciation ? `
      <div class="depreciation-section">
        <h4 style="margin-top: 0;">Depreciation Details</h4>
        <p><strong>Depreciable Basis:</strong> ${formatTaxAmount(data.depreciation.depreciableBasis)}</p>
        <p><strong>Month Placed in Service:</strong> ${data.depreciation.monthPlacedInService}</p>
        <p><strong>Current Year Depreciation:</strong> ${formatTaxAmount(data.depreciation.currentYearDepreciation)}</p>
      </div>
      ` : ''}

      <div class="footer">
        Generated by PropOwl - The wise way to manage rentals<br>
        Report generated on: ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}<br>
        <strong>Important:</strong> This report is for informational purposes only. Consult with a qualified tax professional before filing.
      </div>
    </body>
    </html>
  `;
}

/**
 * Convert multi-property summary to professional HTML
 */
export function summaryToHTML(summary: ScheduleESummary): string {
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>Schedule E Multi-Property Summary - ${summary.taxYear}</title>
      <style>
        @page {
          size: A4;
          margin: 1in 0.75in;
        }
        body {
          font-family: Arial, sans-serif;
          font-size: 11px;
          line-height: 1.3;
          margin: 0;
          color: #000;
          -webkit-print-color-adjust: exact !important;
          print-color-adjust: exact !important;
          color-adjust: exact !important;
        }
        * {
          -webkit-print-color-adjust: exact !important;
          print-color-adjust: exact !important;
          color-adjust: exact !important;
        }
        @media print {
          body {
            font-size: 10px;
            line-height: 1.2;
          }
          .schedule-table {
            font-size: 9px;
          }
          .header {
            margin-bottom: 15px;
          }
          .property-info {
            margin: 10px 0;
            padding: 8px;
          }
        }
        .header {
          text-align: center;
          margin-bottom: 20px;
          border-bottom: 2px solid #000;
          padding-bottom: 10px;
        }
        .summary-table {
          width: 100%;
          border-collapse: collapse;
          margin: 15px 0;
        }
        .summary-table th, .summary-table td {
          border: 1px solid #000;
          padding: 8px;
          text-align: left;
        }
        .summary-table th {
          background: #f0f0f0;
          font-weight: bold;
        }
        .amount {
          text-align: right;
          font-family: 'Courier New', monospace;
        }
        .total-row {
          background: #e8f5ff;
          font-weight: bold;
        }
        .property-section {
          margin-top: 30px;
          page-break-before: auto;
        }
        .footer {
          margin-top: 30px;
          padding-top: 15px;
          border-top: 1px solid #ccc;
          font-size: 9px;
          text-align: center;
          color: #666;
        }
      </style>
    </head>
    <body>
      <div class="header">
        <div style="font-size: 16px; font-weight: bold; margin: 5px 0;">SCHEDULE E MULTI-PROPERTY SUMMARY</div>
        <div style="font-size: 12px; margin: 5px 0;">Tax Year ${summary.taxYear}</div>
        <div style="font-size: 11px; margin: 5px 0;">Portfolio Overview - ${summary.properties.length} Properties</div>
      </div>

      <table class="summary-table">
        <thead>
          <tr>
            <th style="width: 40%;">Property</th>
            <th style="width: 15%;" class="amount">Income</th>
            <th style="width: 15%;" class="amount">Expenses</th>
            <th style="width: 15%;" class="amount">Depreciation</th>
            <th style="width: 15%;" class="amount">Net Income</th>
          </tr>
        </thead>
        <tbody>
          ${summary.properties.map((property, index) => `
            <tr>
              <td><strong>Property ${String.fromCharCode(65 + index)}:</strong><br>${property.property.address.street}${property.property.address.streetLine2 ? `, ${property.property.address.streetLine2}` : ''}<br>${property.property.address.city}, ${property.property.address.state}</td>
              <td class="amount">${formatTaxAmount(property.income.rentalIncome)}</td>
              <td class="amount">${formatTaxAmount(property.totals.totalExpenses - property.expenses.depreciation)}</td>
              <td class="amount">${formatTaxAmount(property.expenses.depreciation)}</td>
              <td class="amount">${property.totals.netIncome < 0 ? `(${formatTaxAmount(Math.abs(property.totals.netIncome))})` : formatTaxAmount(property.totals.netIncome)}</td>
            </tr>
          `).join('')}
          <tr class="total-row">
            <td><strong>PORTFOLIO TOTAL</strong></td>
            <td class="amount">${formatTaxAmount(summary.totals.totalIncome)}</td>
            <td class="amount">${formatTaxAmount(summary.totals.totalExpenses - summary.totals.totalDepreciation)}</td>
            <td class="amount">${formatTaxAmount(summary.totals.totalDepreciation)}</td>
            <td class="amount">${summary.totals.netIncome < 0 ? `(${formatTaxAmount(Math.abs(summary.totals.netIncome))})` : formatTaxAmount(summary.totals.netIncome)}</td>
          </tr>
        </tbody>
      </table>

      ${summary.properties.map((property, index) => `
        <div class="property-section">
          <h3>Property ${String.fromCharCode(65 + index)}: ${property.property.address.street}${property.property.address.streetLine2 ? `, ${property.property.address.streetLine2}` : ''}, ${property.property.address.city}, ${property.property.address.state}</h3>
          <table style="width: 60%; border-collapse: collapse;">
            <tr style="border: 1px solid #000; background: #e8f5e8;">
              <td style="padding: 5px; border: 1px solid #000;"><strong>Line 3. Rents received</strong></td>
              <td style="padding: 5px; border: 1px solid #000; text-align: right; font-family: 'Courier New', monospace;"><strong>${formatTaxAmount(property.income.rentalIncome)}</strong></td>
            </tr>
            <tr style="border: 1px solid #000;">
              <td style="padding: 5px; border: 1px solid #000;">Line 20. Total expenses</td>
              <td style="padding: 5px; border: 1px solid #000; text-align: right; font-family: 'Courier New', monospace;">${formatTaxAmount(property.totals.totalExpenses)}</td>
            </tr>
            <tr style="border: 1px solid #000; background: #e8f5ff;">
              <td style="padding: 5px; border: 1px solid #000;"><strong>Line 21. Income or (loss)</strong></td>
              <td style="padding: 5px; border: 1px solid #000; text-align: right; font-family: 'Courier New', monospace;"><strong>${property.totals.netIncome < 0 ? `(${formatTaxAmount(Math.abs(property.totals.netIncome))})` : formatTaxAmount(property.totals.netIncome)}</strong></td>
            </tr>
          </table>
        </div>
      `).join('')}

      <div class="footer">
        Generated by PropOwl - The wise way to manage rentals<br>
        Report generated on: ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}<br>
        <strong>Important:</strong> This report is for informational purposes only. Consult with a qualified tax professional before filing.
      </div>
    </body>
    </html>
  `;
}

/**
 * Convert text content to simple HTML for PDF generation (fallback)
 */
export function textToHTML(): string {
  // For backwards compatibility, but we'll use the new functions above
  return scheduleEToHTML({} as ScheduleEData);
}